### ISSUE TITLE
Admin sayfasının oluşturulması.

### ISSUE THREAD

**Issue by mberkyuksel** [bahadircolak44/Bil372Proje#4]

**Comment by bahadircolak44** [comment]
oluşturuldu. Başka yapılacak işler tanımlanmalı

**Comment by mberkyuksel** [comment]
onayla butonunun yanına reddetme butonunun konulması # @bahadircolak44

**Comment by daghansengoren** [comment]
admin sayfasına secilen okulun, tedarikcinin veya yardimseverin silinmesi ozelligi getirilecek.
